spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  data:
    rest:
      basePath: /datarest
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    name: hw16-springBootActuatorSpringDataRest.log