DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS(ID IDENTITY PRIMARY KEY,
                     FORENAME VARCHAR(255),
                     SURNAME VARCHAR(255));

CREATE TABLE GENRES(ID IDENTITY PRIMARY KEY,
                    NAME VARCHAR(255));

CREATE TABLE BOOKS(ID IDENTITY PRIMARY KEY,
                   TITLE VARCHAR(255),
                   AUTHORID BIGINT, FOREIGN KEY (AUTHORID) REFERENCES AUTHORS(ID),
                   GENREID BIGINT, FOREIGN KEY (GENREID) REFERENCES GENRES(ID));