spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true