spring:
  data:
    mongodb:
      port: 0
      database: librarydb

  mvc:
    hiddenmethod:
      filter:
        enabled: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.sladkov.otus.spring.hw11.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local