spring:
  data:
    mongodb:
      port: 0
      database: librarydb
  shell:
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.sladkov.otus.spring.hw08.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
