version: "3.8"
services:
  h2db:
    image: "oscarfonts/h2:alpine"
    ports:
      - "5433:81"
    environment:
      - H2_OPTIONS=-ifNotExists

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - h2db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2db:1521/librarydb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa


